### ISSUE TITLE
jacqinthebox/windowsserver2016core got problem with SID - Sysprep needed

### ISSUE THREAD

**Issue by daBONDi** [jacqinthebox/packer-templates#1]
When using multiple "jacqinthebox/windowsserver2016core" Boxes to build a Domainserver and join a Server into the Domain, they got the same sid for me

Issue see: 
http://www.thebuttonfactory.nl/?p=2777

All the boxes got SID: S-1-5-21-3182181239-2212841327-159266127

**Comment by jacqinthebox** [comment]
I'm having a hard time implementing this! Still working on it. Unit now the workaround is to do it manually..

**Comment by daBONDi** [comment]
@jacqinthebox I build my own box with a syspreped image on.
sorry i cannot contribute the stuff into a public repo to show you because its company internal :-(

# Tasks After Build
- Copy unattend.xml for sysprep into vm
- Start Sysprep over shutdown_command: "shutdown_command":"a:/sysprep.bat"
```
--- sysprep.bat ---
C:/windows/system32/sysprep/sysprep.exe /generalize /oobe /quiet /unattend:C:/Windows/Panther/Unattend/unattend.xml /shutdown
```

If you want to Execute something after you start a new clone of the box
put a Batchfile named "SetupComplete.cmd" into "c:/windows/Setup/Scripts/SetupComplete.cmd"

After you Startup the new clone, it starts in the OOBE Mode "Out of Box Expirence" and there it will generate a new id

**Comment by jacqinthebox** [comment]
Fixed this, please see https://atlas.hashicorp.com/jacqinthebox/boxes/windowsserver2016core.
